### ISSUE TITLE
Handling errors with JsonApiView

### ISSUE THREAD

**Issue by alysson-azevedo** [josbeir/cakephp-json-api#2]
I notice that when MissingViewVarException is raised, it is handled by the default ExceptionRenderer and it does use the default AppView to render the error.

I think it'd be good if JsonApiView handled errors too, following the [docs conventions](http://jsonapi.org/format/#error-objects).

**Comment by alysson-azevedo** [comment]
i'm able to deal with this by creating a new template file called `missing_view_var.ctp` at `Template/Error/jsonapi/` directory.

But if you help me with some details, i can make a pull request.

**Comment by josbeir** [comment]
Hi,

Yeah i'm aware of improper error handling.
I'll try to take a look at it this weekend!

PR's are always welcome

**Comment by bravo-kernel** [comment]
You may want to use this [ExceptionRenderer](https://github.com/bravo-kernel/crud/blob/3e850ccd55174e807f551fee665fc827e3248567/src/Error/JsonApiExceptionRenderer.php) I created while working on [JSON API support for the Crud plugin](https://github.com/FriendsOfCake/crud/pull/445).

**Comment by josbeir** [comment]
nice!

Are you willing want to make a PR + some tests for this functionality?

**Comment by bravo-kernel** [comment]
Not really, I am focusing all my effort on the Crud plugin but you should be able to just copy/paste this renderer. Test will follow on Crud once the solution is "acceptable"

**Comment by josbeir** [comment]
Ok no problem, thanks for all the work on this, i'll incorporate it when i find some time then :-)
