### ISSUE TITLE
Crud plugin?

### ISSUE THREAD

**Issue by bravo-kernel** [josbeir/cakephp-json-api#8]
Sorry for the lazy question but would this work when combined with the [Crud plugin](https://github.com/FriendsOfCake/crud)?

**Comment by bravo-kernel** [comment]
Closing as it looks like this could indeed work. Tested while attempting a Crud JsonApiListener.

**Comment by josbeir** [comment]
Thanks for checking, didn't know for sure but was expecting it because of the way its implemented :-)
